version = 1

[[analyzers]]
name = "javascript"

  [analyzers.meta]
  plugins = ["react"]
  environment = [
    "nodejs",
    "mocha",
    "jest"
  ]

[[analyzers]]
name = "test-coverage"
enabled = true