
services:
  mongodb:
    image: mongo:6.0.13
    restart: always
    ports:
      - "27015:27017"
    volumes:
      - ./db-dump/mongo/data:/data/db
      - ./db-dump/mongo/config:/etc/mongod.conf
      - ./db-dump/mongo/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mongo", "--eval", "db.adminCommand('ping')"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s